name: "Build Flutterwave WooCommerce"
description: "Build Flutterwave WooCommerce plugin"

outputs:
  release-filename:
    description: "The name of the release filename"
    value: ${{ steps.build_plugin.outputs.RELEASE_FILENAME }}

runs:
  using: composite
  steps:
    - name: "Install WP-CLI"
      id: install_wp_cli
      shell: bash
      run: |
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        chmod +x wp-cli.phar
        sudo mv wp-cli.phar /usr/local/bin/wp
    - name: "Build the plugin"
      id: build_plugin
      shell: bash
      env:
        RELEASE_FILENAME: "rave-woocommerce-payment-gateway.zip"
      run: |
        nvm install
        nvm use
        npm install
        npm run build
        
        if [[ ! -f $RELEASE_FILENAME ]]; then
          echo "::error::Failed to create release archive $RELEASE_FILENAME."
          exit 1
        fi
        
        echo "RELEASE_FILENAME=$RELEASE_FILENAME" >> $GITHUB_OUTPUT