name: Publish to WordPress.org
on:
    release:
        types: [released]
jobs:
    tag:
        name: New Release
        runs-on: ubuntu-latest
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        steps:
            - uses: act10ns/slack@v2
              with:
                  status: starting
              if: ${{ always() }}
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Build Plugin
              uses: ./.github/actions/make-build
            - name: WordPress Plugin Deploy
              id: deploy
              uses: 10up/action-wordpress-plugin-deploy@stable
              env:
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                  SLUG: rave-woocommerce-payment-gateway
            - name: Upload release asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: ${{github.workspace}}/woocommerce-rave.zip
                  asset_name: woocommerce-rave.zip
                  asset_content_type: application/zip
            - uses: act10ns/slack@v2
              with:
                  status: ${{ job.status }}
                  steps: ${{ toJson(steps) }}
              if: ${{ always() }}